# Generated by Django 4.2.5 on 2023-09-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_price_product_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, null=True)),
                ('kelas', models.CharField(max_length=255, null=True)),
                ('aplikasi', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
